DROP TABLE IF EXISTS [dbo].[00_pocet_obyvatel];

CREATE TABLE [dbo].[00_pocet_obyvatel]
(
    okres_nazev    nvarchar(100),
    orp_nazev      nvarchar(100),
    orp_kod        nvarchar(100),
    okres_kod      nvarchar(100),
    vekova_skupina nvarchar(100),
    pocet_obyvatel nvarchar(100)
);

INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel)
VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'0-17', N'2 827');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'0-17', N'3 950');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'0-17', N'4 772');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'0-17', N'3 376');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'0-17', N'27 378');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'0-17', N'3 723');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'0-17', N'9 005');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'0-17', N'4 665');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'0-17', N'11 086');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'0-17', N'2 412');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'0-17', N'2 550');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'0-17', N'3 099');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'0-17', N'6 442');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'0-17', N'11 444');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'0-17', N'5 160');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'18-24', N'940');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'18-24', N'1 371');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'18-24', N'1 585');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'18-24', N'1 077');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'18-24', N'9 226');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'18-24', N'1 223');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'18-24', N'3 040');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'18-24', N'1 527');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'18-24', N'3 762');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'18-24', N'768');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'18-24', N'850');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'18-24', N'1 051');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'18-24', N'2 203');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'18-24', N'3 832');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'18-24', N'1 854');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'25-29', N'932');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'25-29', N'1 223');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'25-29', N'1 507');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'25-29', N'1 036');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'25-29', N'8 267');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'25-29', N'1 153');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'25-29', N'2 865');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'25-29', N'1 442');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'25-29', N'3 311');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'25-29', N'754');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'25-29', N'753');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'25-29', N'1 118');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'25-29', N'2 045');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'25-29', N'3 527');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'25-29', N'1 460');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'30-34', N'932');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'30-34', N'1 173');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'30-34', N'1 586');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'30-34', N'1 090');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'30-34', N'9 431');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'30-34', N'1 195');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'30-34', N'2 971');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'30-34', N'1 559');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'30-34', N'3 625');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'30-34', N'844');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'30-34', N'844');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'30-34', N'1 068');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'30-34', N'2 218');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'30-34', N'3 897');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'30-34', N'1 670');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'35-39', N'834');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'35-39', N'1 251');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'35-39', N'1 590');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'35-39', N'1 113');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'35-39', N'9 897');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'35-39', N'1 262');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'35-39', N'3 323');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'35-39', N'1 661');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'35-39', N'3 634');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'35-39', N'860');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'35-39', N'832');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'35-39', N'1 073');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'35-39', N'2 302');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'35-39', N'3 931');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'35-39', N'1 760');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'40-44', N'1 069');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'40-44', N'1 614');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'40-44', N'2 056');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'40-44', N'1 461');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'40-44', N'11 705');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'40-44', N'1 559');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'40-44', N'4 019');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'40-44', N'1 995');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'40-44', N'4 618');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'40-44', N'999');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'40-44', N'1 074');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'40-44', N'1 400');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'40-44', N'2 780');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'40-44', N'5 042');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'40-44', N'2 271');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'45-49', N'1 350');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'45-49', N'1 523');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'45-49', N'2 326');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'45-49', N'1 534');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'45-49', N'11 733');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'45-49', N'1 536');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'45-49', N'3 978');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'45-49', N'2 113');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'45-49', N'4 827');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'45-49', N'1 040');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'45-49', N'1 127');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'45-49', N'1 434');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'45-49', N'2 951');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'45-49', N'5 225');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'45-49', N'2 224');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'50-54', N'1 150');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'50-54', N'1 235');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'50-54', N'1 737');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'50-54', N'1 152');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'50-54', N'9 287');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'50-54', N'1 261');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'50-54', N'3 069');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'50-54', N'1 620');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'50-54', N'3 933');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'50-54', N'834');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'50-54', N'896');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'50-54', N'1 149');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'50-54', N'2 156');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'50-54', N'4 349');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'50-54', N'1 860');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'55-59', N'1 031');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'55-59', N'1 215');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'55-59', N'1 675');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'55-59', N'1 120');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'55-59', N'8 717');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'55-59', N'1 189');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'55-59', N'3 039');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'55-59', N'1 554');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'55-59', N'3 821');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'55-59', N'957');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'55-59', N'958');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'55-59', N'1 124');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'55-59', N'2 098');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'55-59', N'3 997');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'55-59', N'1 719');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'60-64', N'942');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'60-64', N'1 260');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'60-64', N'1 628');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'60-64', N'1 135');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'60-64', N'8 628');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'60-64', N'1 125');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'60-64', N'2 939');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'60-64', N'1 431');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'60-64', N'3 753');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'60-64', N'856');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'60-64', N'826');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'60-64', N'1 099');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'60-64', N'1 961');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'60-64', N'3 789');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'60-64', N'1 593');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'65-69', N'1 076');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'65-69', N'1 388');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'65-69', N'1 941');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'65-69', N'1 348');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'65-69', N'9 760');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'65-69', N'1 250');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'65-69', N'3 430');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'65-69', N'1 594');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'65-69', N'4 075');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'65-69', N'795');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'65-69', N'983');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'65-69', N'1 183');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'65-69', N'2 229');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'65-69', N'4 278');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'65-69', N'1 868');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'70-74', N'1 159');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'70-74', N'1 233');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'70-74', N'1 948');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'70-74', N'1 176');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'70-74', N'9 111');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'70-74', N'1 072');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'70-74', N'2 954');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'70-74', N'1 547');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'70-74', N'3 791');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'70-74', N'840');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'70-74', N'924');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'70-74', N'1 126');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'70-74', N'2 060');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'70-74', N'4 133');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'70-74', N'1 902');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'75-79', N'678');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'75-79', N'838');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'75-79', N'1 225');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'75-79', N'780');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'75-79', N'6 606');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'75-79', N'750');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'75-79', N'1 797');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'75-79', N'1 071');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'75-79', N'2 810');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'75-79', N'609');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'75-79', N'692');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'75-79', N'641');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'75-79', N'1 296');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'75-79', N'2 611');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'75-79', N'1 112');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Broumov', N'5201', N'CZ0523', N'80+', N'699');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Dobruška', N'5202', N'CZ0524', N'80+', N'922');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Dvůr Králové nad Labem', N'5203', N'CZ0525', N'80+', N'1 177');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Hořice', N'5204', N'CZ0522', N'80+', N'826');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Hradec Králové', N'5205', N'CZ0521', N'80+', N'7 481');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Jaroměř', N'5206', N'CZ0523', N'80+', N'748');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Jičín', N'5207', N'CZ0522', N'80+', N'2 114');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Kostelec nad Orlicí', N'5208', N'CZ0524', N'80+', N'1 169');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Náchod', N'5209', N'CZ0523', N'80+', N'3 014');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Jičín', N'Nová Paka', N'5210', N'CZ0522', N'80+', N'675');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Náchod', N'Nové Město nad Metují', N'5211', N'CZ0523', N'80+', N'741');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Hradec Králové', N'Nový Bydžov', N'5212', N'CZ0521', N'80+', N'751');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Rychnov n. Kn.', N'Rychnov nad Kněžnou', N'5213', N'CZ0524', N'80+', N'1 372');
INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel) VALUES (N'Trutnov', N'Trutnov', N'5214', N'CZ0525', N'80+', N'2 667');

INSERT INTO [00_pocet_obyvatel] (okres_nazev, orp_nazev, orp_kod, okres_kod, vekova_skupina, pocet_obyvatel)
VALUES (N'Trutnov', N'Vrchlabí', N'5215', N'CZ0525', N'80+', N'1 124');
